version: "3.9"

services:
  db:
    image: postgres:17
    container_name: postgres-chat-llm
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_HOST}"]
      interval: 2s
      timeout: 2s
      retries: 10
  
  backend:
    build: .
    container_name: backend-chat-llm
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8080:8080"

volumes:
  pgdata:
